#!/bin/sh

BASEDIR=$(dirname "$0")
FILE="$BASEDIR/../src/version.ml"

# Git version information
GIT_REV=$(git log --pretty=format:'%h' -n 1)
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_TIME=$(git show -s --format=%cs ${GIT_REV})

echo "(* This file is auto-generated by `generate-version-ml.sh` *)" > $FILE
echo "let git_revision = \"${GIT_REV}\"" >> $FILE
echo "let git_branch = \"${GIT_BRANCH}\"" >> $FILE
echo "let git_time = \"${GIT_TIME}\"" >> $FILE
